name: "Repo B CI"

on:
  repository_dispatch:
    types: 
      - create
      - delete

jobs:
  execute:
    runs-on: ubuntu-18.04
    outputs:
      payload: ${{ github.event.client_payload }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test
        run: cat test.txt
      
      - name: Log
        shell: bash
        run: |
          echo "${{ github.event.action }}"
          echo ${{ github.event.client_payload.sha }}
