name: "Repo B CI"

on:
  repository_dispatch:
    types: 
      - trigger

jobs:
  execute:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test
        run: cat test.txt

      - name: Log
        shell: bash
        run: |
          echo ${{ github.event.client_payload.sha }}
