name: "Repo B CI"

on:
  repository_dispatch:
    types: 
      - create
      - delete

jobs:
  execute:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test
        run: cat test.txt

      - name: Log
        shell: bash
        run: |
          echo ${{ github.event.client_payload.sha }}

      - name: Log 2
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('${{ github.event }}')
